### ISSUE TITLE
Request system to build packages

### ISSUE THREAD

**Issue by kernelb00t** [bionade24/abs_cd#24]
That's a very weird but creative idea I had. 

We could use your system to build Makepkg files for non-powerful laptops/IoT/some old home computers that cannot handle building a kernel, while making it completely autonomous (i.e. without requiring an admin to fetch the latest Makepkg, build it, get the package test it, then copy it on its own mirror).

In a beautiful world, a user would:
1- Check for updates by lauching `yay` for example.
2- Review which packages are for upgrade, and review diffs of AUR repos.
3- A Yay hook gets Makepkg files, sends them to the build system for (obviously) build.
4- During this time, Yay updates what can be upgradeable (official repo packages for example) and the build server builds.
5- At the end of Yay's upgrades, Yay pings the build server for availability of packages and upgrades those that ended. When no other packages are available (if some are still building) Yay shows a prompt to the user saying "Do you want to wait for packages X Y and Z to build?" and exits if no.
6- Yay signals its exit to the build server
7- When the build server is done with a package and Yay is not waiting for packages (i.e. exited), it sends an email to the user saying "Your package is ready". 
8- When reexecuting `yay`, it will check for updates, send the Makepkg files, and gets states of built packages from the server.

Server-side, this would mean getting requests from either an API or SSH. It will call abs_cd for building the package. When done, the server moves the successfully built package into the user's custom mirror and checks with the notification service for sending a state update.

The big plus would be that 24/7 homelab servers can be used to auto build software. This would allow houses of nerds with 2+ Arch computers at home, not always very powerful, to build and share built packages between computers. Building into containers is sticking to Arch Linux philosophy. Each client could send some patches or drop-ins for the makepkg.conf file to use some custom build flags so that the built package has maximum efficiency on the computer. 

The downside is that it would be hard on networking, and increases complexity when dealing with packaging issues.

Is it something a lot of people would benefit, or no?

**Comment by bionade24** [comment]
Hi, it's in an interesting idea to consider, but I don't see how this overlaps a lot with the targets that this program tries to solve. Some exemplary points:

> - Check for updates by lauching yay for example.

This means that basically you have to have some AUR helper locally installed that queries the AUR website for updates first to get the CD going.  If you'd instead start tracking all packges in the CD after the 1st time they've been requested, the maintanance effort would move into removing packages you don't need anymore from the CD.

This also does not handle a common AUR problem: No pkgrel increases when a rebuild is neceassary for ABI compatibility. You would have to find some sensible way for this or build everytime.

ABS-CD was orginally created to mirror hundreds of AUR packages from a Github org to the AUR only on successfull builds while having a web-based interface where anyone can read the build logs (in contrast to most similar tools). Having a repo with pkgs to use was more of a nice byproduct, if anything.


>The big plus would be that 24/7 homelab servers can be used to auto build software. This would allow houses of nerds with 2+ Arch computers at home, not always very powerful, to build and share built packages between computers.


> Each client could send some patches or drop-ins for the makepkg.conf file to use some custom build flags so that the built package has maximum efficiency on the computer.

This would basically drop the whole idea of a personal pacman repo. Additionally, those 2 statements also partially contradict each other, as the devices will need different instruction set compiler flags for max performance. 

Most importantly, your scenario is already mostly covered by https://www.distcc.org/ in a more general manner. A lot of people who want this are probably already having their setup with this.

You are of course free to fork my project if you comply with  AGPL3 and implement your ideas, but I don't see them fitting into my vision.
