### ISSUE TITLE
Enhance README, especially development setup.

### ISSUE THREAD

**Issue by fmauch** [bionade24/abs_cd#5]
I've tried to get this run locally in order to test #4. However, after starting it as proposed in the README, I noticed a couple of things:

 - Using `localhost:8000` in the browser results in a Bad Request error. Using `127.0.0.1:8000` works. This might be due to my network / hostname setup, but I am assuming this should work.
 - The current README doesn't contain information on how to login. I assumed that logging into the docker container using `docker exec -it <container-id> bash` and executing `python manage.py createsuperuser` to create a user would be the way to go. If this is correct, that should probably go into the README, as well.
 - There seems to be something wrong with the staticfiles. The whole GUI is completely ugly and navigation to an arbitrary stylesheet (e.g. `http://127.0.0.1:8000/static/admin/css/base.css`) results in a NOT FOUND error page. Did I miss anything there?
 - ~~Triggering a build seems not to work for me. I added an arbitrary package (python-catkin_pkg) and tried to build it. However, it does not show a **building** state in the overview. I assume that without having any dependent packages inside my instance this should still try to build and result in an error if an AUR dependency is missing, right? How could I debug this any further? This might be an issue with docker-in-docker?~~ Must have been a misconception. It seems to work, sorry...

In case of time constraints, please look at #4 first :-)

**Comment by bionade24** [comment]
> I've tried to get this run locally in order to test #4. However, after starting it as proposed in the README, I noticed a couple of things:
> 
> * Using `localhost:8000` in the browser results in a Bad Request error. Using `127.0.0.1:8000` works. This might be due to my network / hostname setup, but I am assuming this should work.
> * The current README doesn't contain information on how to login. I assumed that logging into the docker container using `docker exec -it <container-id> bash` and executing `python manage.py createsuperuser` to create a user would be the way to go. If this is correct, that should probably go into the README, as well.
Yeah, forgot that. I'm not good at writing READMEs. It's somewhat a standard Django procedure and I believe I mentioned it's Django, glad you found it.
> * There seems to be something wrong with the staticfiles. The whole GUI is completely ugly and navigation to an arbitrary stylesheet (e.g. `http://127.0.0.1:8000/static/admin/css/base.css`) results in a NOT FOUND error page. Did I miss anything there?
Yes, you're running with the production server. You have to set `DEBUG=True` to allow django to serve static files.
> * ~Triggering a build seems not to work for me. I added an arbitrary package (python-catkin_pkg) and tried to build it. However, it does not show a **building** state in the overview. I assume that without having any dependent packages inside my instance this should still try to build and result in an error if an AUR dependency is missing, right? How could I debug this any further? This might be an issue with docker-in-docker?~ Must have been a misconception. It seems to work, sorry...
> 
> In case of time constraints, please look at #4 first :-)
Sorry, but this was just too easy to answer only took me some seconds. I will look at it at least next weekend, don't want to promise I'm doing it earlier.
